version: '3.9'

volumes:
  static:
  media:
  pg_data:

services:
  db:
    image: postgres:13
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file: .env

  backend:
    image: fenixzip/foodgram_backend
    restart: always
    volumes:
      - static:/app/static/
      - media:/app/media/
    env_file: .env
    depends_on:
      - db

  frontend:
    image: fenixzip/foodgram_frontend
    volumes:
      - ./frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: fenixzip/foodgram_ngnix
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - backend
